# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - helm
chart-repos:
  - prometheus=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
helm-extra-args: --timeout 600s