FROM alpine:latest

WORKDIR /opt/

COPY easeprobe /opt/
COPY resources/scripts/entrypoint.sh /
RUN apk update && apk add tini tzdata busybox-extras curl redis mysql-client

ENV PATH /opt/:$PATH
ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]
