FROM --platform=$BUILDPLATFORM alpine:latest

WORKDIR /opt/

COPY bin/easeprobe /opt/
COPY resources/scripts/entrypoint.sh /
RUN apk update && apk add tini tzdata busybox-extras curl redis

ENV PATH /opt/:$PATH
ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]
